### PR TITLE
Hid saving status if working id is present

### PR DESCRIPTION
**Pull request by MitchelPaulin**
https://rally1.rallydev.com/#/57732444928ud/custom/373260458992?detail=%2Fuserstory%2F630747617771

The saving status component is a pretty dumb component https://github.com/Brightspace/d2l-save-status/blob/master/d2l-save-status.js. It doesn't send events or do any logic, it mostly relies on us telling it what state to show and doesn't send anything for us to consume. 

Because of this there was really no change needed, hiding the saving component has no effect on events, since this was a pretty small ticket and because I needed to do it to test anyways I also just added the logic to hide the saving status indicator if we have a working copy id 

This also covers two additional tickets:
- [Removed publish warning](https://rally1.rallydev.com/#/57732444928ud/custom/373260458992?detail=%2Fuserstory%2F630663183315)
- [Remove the saved and saving field from the inline view](https://rally1.rallydev.com/#/57732444928d/dashboard?detail=%2Fuserstory%2F630652590645)

### CODE REVIEW

**Comment by devpow112** [comment]
Getting some `this._context is not defined` errors.

**Comment by MitchelPaulin** [comment]
> Getting some `this._context is not defined` errors.

Looks like context isn't defined until first update, I'll add some checks for it

**Comment by MitchelPaulin** [comment]
Hiding the warning is desired now https://rally1.rallydev.com/#/57732444928ud/custom/373260458992?detail=%2Fuserstory%2F630663183315

**Comment by devpow112** [comment]
Why did the warning only disappear from the first vdiff for compact assessment?

**Comment by MitchelPaulin** [comment]
> Why did the warning only disappear from the first vdiff for compact assessment?

Its because its the only test with a workingCopyId appended to the assessment-href, see here https://github.com/Brightspace/d2l-rubric/blob/master/test/perceptual/compact-custom-points-assessed.visual-diff.html#L28

**Review by devpow112 — APPROVED** [review]

**Pull request merged**
