### PR TITLE
changed travail to tache

### PR DESCRIPTION
**Pull request by joshvanwijk**
as per TELO request

### CODE REVIEW

**Comment by devpow112** [comment]
@joshvanwijk to get CI to pass you will need to run the steps here to build the language files.
https://github.com/Brightspace/d2l-rubric#modifying-a-lang-term

**Comment by joshvanwijk** [comment]
I'm afraid I don't understand these next steps.
Josh

**Comment by devpow112** [comment]
Ok, I'll take care of these then.

**Comment by joshvanwijk** [comment]
Thank you! I'm very new to the process and am still learning.
Josh

**Pull request merged**
