### PR TITLE
Disabled stuctural edit options from appearning in the UI in partial edit mode

### PR DESCRIPTION
**Pull request by MitchelPaulin**
Fixes a couple bugs I came across when implementing the partial edit vdiff tests, the actions were rejected correctly by the back end so only front end changes required here
- https://rally1.rallydev.com/#/57732444928ud/custom/373260458992?detail=%2Fdefect%2F628601079467
- https://rally1.rallydev.com/#/57732444928ud/custom/373260458992?detail=%2Fdefect%2F628429463277

### CODE REVIEW

**Review by imcdonald-d2l — APPROVED** [review]

**Comment by devpow112** [comment]
Well that sadly failed @MitchelPaulin. Not exactly sure why https://github.com/Brightspace/d2l-rubric/runs/5483543720?check_suite_focus=true.

**Comment by MitchelPaulin** [comment]
> Well that sadly failed @MitchelPaulin. Not exactly sure why https://github.com/Brightspace/d2l-rubric/runs/5483543720?check_suite_focus=true.

Damn, guess I'll do a manual one

**Comment by devpow112** [comment]
So far I've had this work 50% of the time. I may have to look into making it more robust (look into changing the action itself)

**Pull request merged**
