### PR TITLE
Criterion Editor overlay scrolls properly with select-outcomes

### PR DESCRIPTION
**Pull request by ChrisKraljevicD2L**
Needs [this activity alignments PR](https://github.com/Brightspace/d2l-activity-alignments/pull/57)

### CODE REVIEW

**Comment by ChrisKraljevicD2L** [comment]
I'll merge this guy when I cut a new activity alignments release

**Comment by ChrisKraljevicD2L** [comment]
From CI: `window._wctCallback is not a function`?

**Comment by djwester** [comment]
@mpharoah-d2l  is the error from changing the polyfill  in d2l-table? It looks like it was fine on chrome but failed on firefox

**Comment by iFun** [comment]
@ChrisKraljevicD2L is there something wrong with this PR not being able merged

**Pull request merged**
