### PR TITLE
bypassing d2l-input-text validation

### PR DESCRIPTION
**Pull request by dlockhart**
Context: d2l-input-text is about to have validation enabled, which will suddenly start checking for min/max/required and a few other attributes. Since we're not sure how this will impact places that weren't expecting validation to suddenly start happening, we're disabling it.

### CODE REVIEW

**Comment by dlockhart** [comment]
I'm guessing merging this isn't going to update & release.... seems to be manual.

**Comment by djwester** [comment]
Yes, update and release of this repo is manual.

**Comment by dlockhart** [comment]
@djwester Build is failing due to a syntax error in the Finnish lang file. I can fix that (a string just needs to be escaped), but Finnish isn't even a language we need to support and the file is in English anyway... so I can also just remove it. Thoughts?

**Comment by djwester** [comment]
I don't exactly remember the details, but I think we need to have the file there even though it only has English in it, otherwise we end up with some errors. 

Also, once that is fixed I think there might still be a test failure (about holistic rubrics) that you don't need to worry about for now. This repo needs a bit of love soon :)

**Pull request merged**
