### PR TITLE
deps: polymer-siren-behaviors 0.3.1

### PR DESCRIPTION
**Pull request by omsmith**
I ran `./node_modules/.bin/polymer test --skip-plugin=sauce` and it passed

### CODE REVIEW

**Comment by omsmith** [comment]
https://github.com/Brightspace/polymer-siren-behaviors/compare/v0.1.0...v0.3.1

This bump inspired by the need/desire to use the new 0.3.x functionality in d2l-activity-alignments, which is also part of BSI

**Comment by omsmith** [comment]
Only iffy bit i noted is here: https://github.com/Brightspace/d2l-rubric/blob/4fe034663ce22c1cc433b6a4ae61282e7d1032fe/editor/d2l-rubric-editor.html#L281

`.update` is and always was `Promise`, but we're a couple extra microtasks away now. Seems like things will probably continue to probably work though.

**Comment by mdgbayly** [comment]
@omsmith Sorry, missed this. Do we need to co-ordinate on the BSI bump with `d2l-activity-alignments` or can this be merged at any time and a BSI bump done with the new version of `polymer-siren-behaviors`

**Comment by omsmith** [comment]
No worries. Thanks @mdgbayly. I'll merge now, get them all updated, and into BSI.

**Pull request merged**
