### PR TITLE
Rubric feedback print styles - US133167

### PR DESCRIPTION
**Pull request by imcdonald-d2l**
- removes feedback arrow in print view
- remove `position: relative;` as it was messing with some print styles. See example:

| Before | After |
| --- | --- |
| position-relative | position-relative-fixed |

### CODE REVIEW

**Comment by jesseag** [comment]
> * removes feedback arrow in print view
> * remove `position: relative;` as it was messing with some print styles. See example:
> 
> Before	After
> position-relative	position-relative-fixed

Is it okay that the checkmark is overtop of criterion name?

**Comment by imcdonald-d2l** [comment]
> Is it okay that the checkmark is overtop of criterion name ("amet ipsum") in the after picture?

Yeah, that is not ideal. I'll see if I can add some padding to the text so we can avoid that.

**Comment by imcdonald-d2l** [comment]
@jesseag issue is now fixed!
| Before | After |
| --- | --- |
| check-before | check-after |

**Review by MitchelPaulin — APPROVED** [review]

**Review by jesseag — APPROVED** [review]
Looks alright to me. It bugs me that we have to use hardcoded values sometimes but in this case I think it makes sense.

**Review by devpow112 — APPROVED** [review]

**Pull request merged**
