### PR TITLE
Update to latest d2l-activity-alignments

### PR DESCRIPTION
**Pull request by devpow112**
Gets us some accessibility fixes.

### CODE REVIEW

**Comment by devpow112** [comment]
Found a small issue in d2l-activity-alignments fixing that first.

**Comment by devpow112** [comment]
> Found a small issue in d2l-activity-alignments fixing that first.

Will update once https://github.com/Brightspace/d2l-activity-alignments/pull/158 merges/releases.

**Review by mpharoah-d2l — APPROVED** [review]

**Comment by devpow112** [comment]
Found another issue

https://github.com/Brightspace/d2l-activity-alignments/pull/159

**Comment by devpow112** [comment]
Styling issues are fixed. Sorry for the misstep there 😞.

**Comment by devpow112** [comment]
Abandoning. There's still another change needed for activity alignments based on yet another fix to multi-select

**Pull request closed without merging**
